CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.MARKET_REPORTS (
    ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    SYMBOLS VARCHAR(255) NOT NULL,
    MARKET_CONTEXT VARCHAR(16777216),
    REPORT VARCHAR(16777216) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.STOCK_PICKS (
    ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    REPORT_ID NUMBER,
    SYMBOL VARCHAR(20) NOT NULL,
    STOCK_NAME VARCHAR(100),
    REASON VARCHAR(16777216) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.STOCK_ORDERS (
    ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PICK_ID NUMBER,
    SYMBOL VARCHAR(20) NOT NULL,
    BUY_PRICE NUMBER(18, 2),
    BUY_QTY NUMBER,
    ORDER_SUCCESS BOOLEAN,
    ORDER_RAW VARCHAR(16777216),
    ORDERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.STOCK_MASTER (
    SHORT_CODE VARCHAR(20) NOT NULL,
    STANDARD_CODE VARCHAR(30) NOT NULL,
    STOCK_NAME VARCHAR(200) NOT NULL,
    MARKET_NAME VARCHAR(20),
    CREATE_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SHORT_CODE)
);

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.BOT_TRADE (
    TRADE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    BOT_ID NUMBER NOT NULL,
    SYMBOL VARCHAR(100) NOT NULL,
    SELECT_REASON VARCHAR(1000),
    BUY_PRICE NUMBER(18, 4),
    BUY_AT TIMESTAMP_NTZ NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
