CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.MARKET_REPORTS (
    ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    SYMBOLS VARCHAR(255) NOT NULL,
    MARKET_CONTEXT VARCHAR(16777216),
    REPORT VARCHAR(16777216) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.STOCK_PICKS (
    ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    REPORT_ID NUMBER,
    SYMBOL VARCHAR(20) NOT NULL,
    STOCK_NAME VARCHAR(100),
    REASON VARCHAR(16777216) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);
